import os

def get_csharp_files(directory):
    csharp_files = []
    for root, dirs, files in os.walk(directory):
        # Exclude directories named "migrations" (case insensitive)
        dirs[:] = [d for d in dirs if d.lower() != 'migrations']
        for file in files:
            if file.endswith(".cs"):
                csharp_files.append(os.path.join(root, file))
    return csharp_files

def is_auto_generated(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            if '<auto-generated' in line:
                return True
    return False

def read_files(files):
    all_code = ""
    for file in files:
        if is_auto_generated(file):
            print(f"Skipping auto-generated file: {file}")
            continue
        
        with open(file, 'r', encoding='utf-8') as f:
            all_code += f"// File: {file}\n"
            all_code += f.read()
            all_code += "\n\n"
    return all_code

def main():
    project_directory = input("Enter the path to your project directory: ")
    csharp_files = get_csharp_files(project_directory)
    if not csharp_files:
        print("No C# files found in the specified directory.")
        return
    
    all_code = read_files(csharp_files)
    
    # Save the combined code to a file
    with open("combined_csharp_code.txt", 'w', encoding='utf-8') as output_file:
        output_file.write(all_code)
    
    print("All C# code has been written to combined_csharp_code.txt")

if __name__ == "__main__":
    main()
